Happy Thoughts API Sandra
Technigo/project-happy-thoughts-api pull request #104
Opened 2021-01-08 23:57 UTC by sandra-shumanteva-kaevska

I have done the blue level.

Here is link to my frontend:
https://github.com/sandra-shumanteva-kaevska/project-happy-thoughts

2021-01-12 18:38 UTC, sofiavazs approved these changes
Nice job Sandra! Your app works as intended and well done connecting the backend to the frontend! Really easy to read code and nice error handling!

2021-01-12 18:38 UTC, sofiavazs commented on README.md
> +https://happy-thoughts-sandra.herokuapp.com/
👏🏻

2021-01-12 18:38 UTC, sofiavazs commented on server.js
> +})
Nice! Mathes the requirements

2021-01-12 18:38 UTC, sofiavazs commented on server.js
>  })
👏🏻

2021-01-12 18:38 UTC, sofiavazs commented on server.js
> +})
Nice structure and error handling!

2021-01-19 13:08 UTC, KarolCislowski requested changes
Please add a link to a frontend to your `README` file.

2021-01-19 13:31 UTC, sandra-shumanteva-kaevska commented
> Please add a link to a frontend to your `README` file.

done :)

2021-01-19 15:01 UTC, KarolCislowski approved these changes
Great work 💯

2021-03-09 13:33 UTC, closed without merging