Happy-thoughts-API Sara Stjernberg
Technigo/project-happy-thoughts-api pull request #119
Opened 2021-01-10 16:16 UTC by stjernberg

2021-01-19 19:02 UTC, AnnaHellqvist approved these changes
Great job with the project Sara! 💥 Your code looks clean and readable, you could add some comments before the endpoints and explain what they do :)

2021-01-19 19:02 UTC, AnnaHellqvist commented on server.js
> +
you could remove some white space here :)

2021-01-19 19:24 UTC, KarolCislowski requested changes
I sent like 12 of messages from your frontend and only 1 made its way to the database. Please check it.

2021-01-24 15:34 UTC, KarolCislowski approved these changes
It works now perfectly 😄

2021-03-09 13:32 UTC, closed without merging