Happy-API
Technigo/project-happy-thoughts-api pull request #121
Opened 2021-01-10 19:09 UTC by lilihorvath

2021-01-17 17:01 UTC, Snabbina commented
Hey Lili, hope you are good! Im supposed to review your project, but the Heroku link does not seem to work... de deployed link should look something like this "https://name-oftheproject-api.herokuapp.com/" and plz also add the deployed link to the frontend so I can check that out too for you! /Have a nice evening! /S

2021-01-20 18:36 UTC, KarolCislowski requested changes
Please change wrong endpoints and add a link to the hosted frontend. 😺

2021-01-20 18:36 UTC, KarolCislowski commented on server.js
> +app.get('/', async (req, res) => {
this endpoint should be `GET /thoughts` 😸

2021-01-20 18:36 UTC, KarolCislowski commented on server.js
> +app.post('/', async (req, res) => {
this endpoint should be `POST /thoughts` 😸

2021-01-20 18:36 UTC, KarolCislowski commented on server.js
> +  },
you created this field in the model, but you never used it. why? 🤔

2021-03-11 09:43 UTC, closed without merging