Project happy thought api
Technigo/project-happy-thoughts-api pull request #133
Opened 2021-01-13 19:26 UTC by destinyleia

2021-01-20 20:14 UTC, KarolCislowski requested changes
Your code looks very nice, but you need to provide links to both frontend and backend for testing purposes. 😸

2021-01-20 20:14 UTC, KarolCislowski commented on server.js
> +  },
Nicely structured data 👍🏻

2021-02-04 17:38 UTC, destinyleia commented
Hi Karol,

Thanks for the review! 

Here's the link to the deployed site https://happy-thoughts-dess.herokuapp.com/thoughts

and heres to the frontend: https://happy-thoughts-happy-life.netlify.app/

Thank you! :D

2021-02-10 13:13 UTC, HIPPIEKICK commented on server.js
> +})
This endpoint doesn't correspond with your frontend. The logic should increment the hearts in your message/thought 👇
```
hearts: {
    type: Number,
    default: 0,
  },
```

2021-02-11 15:40 UTC, destinyleia commented on server.js
> +})
How do I solve it? :) I have no idea... need help :)

2021-02-18 12:51 UTC, HIPPIEKICK commented on server.js
> +})
Have you looked at Stack Overflow or the recorded material? 😇 Here's a link to all questions with the tag project-happy-thoughts-api -> https://stackoverflow.com/c/technigo/questions/tagged/189

2021-02-19 18:35 UTC, destinyleia commented on server.js
> +})
It's solved (I think) :) Please review! :D

2021-02-22 14:12 UTC, HIPPIEKICK commented on server.js
> +})
You've forgotten to update the frontend with the URL to your personal API, so no way to test it! The code looks good though

2021-02-22 14:13 UTC, HIPPIEKICK commented on server.js
> +})
Although I can't like even in Postman. Maybe change the default to 0 instead of `() => 0`

2021-03-01 15:44 UTC, HIPPIEKICK commented on server.js
> +})
Your frontend still looks like it has the technigo-url 🤔

2021-03-11 09:43 UTC, closed without merging