Happy thoughts api
Technigo/project-happy-thoughts-api pull request #135
Opened 2021-01-15 16:02 UTC by BamStugendal

2021-01-15 17:39 UTC, rebkova approved these changes
Very nice job, Bäm! Pretty straightforward code. I have no major comments.

2021-01-15 17:39 UTC, rebkova commented on server.js
> +  const getThoughts = await Thought.find().sort({createdAt: 'desc'}).limit(20).exec()
To make this part more readable, you could write it like that: 
```
const getThoughts = await Thought.find()
.sort({createdAt: 'desc'})
.limit(20)
.exec()
```

2021-01-15 17:39 UTC, rebkova commented on server.js
> +  res.json(getThoughts)
Perhaps return an error if the GET request fails?

2021-01-15 17:39 UTC, rebkova commented on server.js
> +      console.log(err)
Can be removed. And also in line 69.

2021-01-15 17:39 UTC, rebkova commented on server.js
> +// Post a new thought
Very nice with some comments 👍

2021-01-15 17:39 UTC, rebkova commented on server.js
> +})
👍

2021-01-15 17:39 UTC, rebkova commented on server.js
> +
To the point. 🏹

2021-01-20 20:39 UTC, KarolCislowski requested changes
You created a very nice project, but I can't test it fully. Please add a link to the frontend to your `README` file.

2021-01-24 14:23 UTC, KarolCislowski approved these changes
Great project 😸

2021-03-09 13:32 UTC, closed without merging