Project 19 - Petra Almgren
Technigo/project-happy-thoughts-api pull request #137
Opened 2021-01-18 09:32 UTC by petrame

https://project-happy-thoughts.netlify.app/
https://happythoughts-api.herokuapp.com/

2021-01-20 20:52 UTC, KarolCislowski requested changes
This is a very nice code and your frontend is like from a fairytale! 🌈 🦄  Please change your endpoints paths to meet the requirements 😺

2021-01-20 20:52 UTC, KarolCislowski commented on server.js
> +  },
nice data structure 👍🏻

2021-01-20 20:52 UTC, KarolCislowski commented on server.js
> +app.get("/", async (req, res) => {
`/thoughts`

2021-01-20 20:52 UTC, KarolCislowski commented on server.js
> +app.post("/", async (req, res) => {
`/thoughts`

2021-01-20 20:52 UTC, KarolCislowski commented on server.js
> +app.post("/:messageId/like", async (req, res) => {
`/thoughts/:thoughtId/like`

2021-01-23 19:32 UTC, emma-tech reviewed
Good job with the happy thoughts project Petra! Nice, easy to read and well structured code. 
(I can see Karol already left you some comments/changes requested and that you're aware of how to fix those endpoints 🙌)
I also love your frontend, it's so dreamy! 😍🌈

2021-01-23 19:32 UTC, emma-tech commented on server.js
> +      message: "Couldn't save your happy thought, please hold on to it.",
Haha I love the error messages! :) Nice that you made them more fun 🙌

2021-01-23 19:32 UTC, emma-tech commented on server.js
> +    await Message.updateOne(
Good that you remembered about updateOne here 🙌

2021-01-23 19:32 UTC, emma-tech commented on server.js
> +    // Retrieve the information sent by the client to our API endpoint
Good that you comment your code! Makes it easy to follow :)

2021-01-23 19:32 UTC, emma-tech commented on server.js
> +  const messages = await Message.find()
Nice and clean code 👍

2021-01-23 19:34 UTC, emma-tech requested changes
Good job with the happy thoughts project Petra! Nice, easy to read and well structured code.
(I can see Karol already left you some comments/changes requested and that you're aware of how to fix those endpoints 🙌)
I also love your frontend, it's so dreamy! 😍🌈

2021-02-17 09:38 UTC, petrame commented
Endpoints updated

2021-03-09 13:40 UTC, closed without merging