Siri Hemsley - Happy thoughts API
Technigo/project-happy-thoughts-api pull request #143
Opened 2021-05-20 11:02 UTC by sirimatsdotter

This week felt so much easier than last week and I didn't have any problems completing the blue requirements. I didn't prioritise moving further though since I spent some time on my Final project pitch instead. 

Find my API here: https://happy-thoughts-siri.herokuapp.com/
And the front end here: https://awesome-murdock-ef4ca9.netlify.app/

2021-05-26 12:46 UTC, annalenksjo requested changes
Hej Siri,
Nice and well-structured project as always! Great job that you connected it with your front-end as well 👍 
I like that you have some comments in your project, it makes it easier to follow, and I guess for your self as well if you come back to the project later on :-) 

All the endpoints seems so be working fine, and the errormessages too. One suggestion is that you organize your endpoints by method in server.js. I think Max mentioned this in one of the lectures as sort of a standard. 

There is one thing you missed, which is to prevent the possibility to post hearts and Date in the message-post request :-). See my comment in the code. Otherwise the project meets all of the blue requirements. Good job! 🌷

2021-05-26 12:46 UTC, annalenksjo commented on server.js
> +    const savedThought = await new Thought(req.body).save()
Here you have to write (req.body.message) to prevent the possibility to send values for hearts and/or Date, or some other method to prevent this :-)

2021-05-30 15:28 UTC, KarolCislowski requested changes
Please fix your form 😺

2021-05-30 15:28 UTC, KarolCislowski commented on server.js
> +    maxlength: [140, "Message cannot exceed 140 characters"]
Really nice and clean method 😻

2021-05-30 15:28 UTC, KarolCislowski commented on server.js
> +    unique: [true, "Message has to be unique"],
Why you used `unique` here? people can't be happy for the same reasons? 😭

2021-05-30 15:28 UTC, KarolCislowski commented on server.js
> +app.post('/thoughts', async (req, res) => {
I can't send any new message to your API :( it returns an error 400 every time
![image](https://user-images.githubusercontent.com/50926159/120110000-2a957a00-c16c-11eb-9bf5-45b0ed00d5ca.png)

2021-06-08 12:53 UTC, KarolCislowski approved these changes
Great work 🥇

2022-04-21 14:28 UTC, closed without merging