Week 19 - Rasmus Persson
Technigo/project-happy-thoughts-api pull request #146
Opened 2021-05-21 06:53 UTC by rrpersson

Live Project: https://week19-project-happy-thought.herokuapp.com/

2021-05-25 20:27 UTC, CarolineF3 approved these changes
Very clean and readable code, well done!✨ It's nice that you're trying out some new stuff (the exec function and the personalized/customised res.send message).  You might wanna add some documentation in ReadMe to complete your project.

2021-05-30 15:51 UTC, KarolCislowski requested changes
Code looks really good, but:
- Please change maxlength value to 140 characters to meet requirements;
- Please provide a link to the hosted frontend connected to this API in your Readme file.
- Present your app in the readme file in a few lines. It is very important.

2021-05-30 15:51 UTC, KarolCislowski commented on server.js
> +    maxlength: 100,
instruction specified max 140 characters messages.

2021-05-30 15:51 UTC, KarolCislowski commented on server.js
> +    const likes = await Thoughts.updateOne({ _id: id }, { $inc: { heart: 1 } });
👍🏻

2021-05-30 15:51 UTC, KarolCislowski commented on server.js
> +      error: error.errors,
nice error handling 👍🏻

2021-05-30 15:57 UTC, rrpersson commented
I've changed the code and ReadMe. I don't have it connectd to a frontend since that was not part of the assignment.

2021-06-12 15:47 UTC, KarolCislowski approved these changes
Nice App

2022-04-21 14:28 UTC, closed without merging