Week 19 - Darcy
Technigo/project-happy-thoughts-api pull request #148
Opened 2021-05-21 11:44 UTC by darcywinterhill

2021-05-27 07:20 UTC, Aepera approved these changes
Great work! Cannot find anything to not approve 👌👸✔

2021-05-27 07:20 UTC, Aepera commented on README.md
> +
Good descriptions of endpoints.

2021-05-27 07:20 UTC, Aepera commented on server.js
> +      error
Nice and clear error handling 👍

2021-05-27 07:20 UTC, Aepera commented on server.js
> +   maxlength: [140, 'Maximum length is 140 characters']
Great sending some extra information about the requirements.

2021-05-27 07:20 UTC, Aepera commented on server.js
> +    })
I guess this is  middleware handling if server is unavailable and sending error message? Very nice adding this to the app. 🎉

2021-05-30 15:59 UTC, KarolCislowski requested changes
Your code looks nice but You need to provide a link to the hosted frontend connected to this API. 😸

2021-05-30 15:59 UTC, KarolCislowski commented on server.js
> +   maxlength: [140, 'Maximum length is 140 characters']
great configured field 🥳

2021-05-30 15:59 UTC, KarolCislowski commented on server.js
> +    const thoughts = await Thought.find().sort({ createdAt: 'desc' }).limit(20).exec()
💯

2021-05-30 15:59 UTC, KarolCislowski commented on server.js
> +      { new: true }
Nice 👍🏻

2021-06-08 05:44 UTC, KarolCislowski approved these changes
Great Project!

2022-04-21 14:28 UTC, closed without merging