Week19 Yennie Happy-Thought-API
Technigo/project-happy-thoughts-api pull request #153
Opened 2021-05-21 14:47 UTC by Yennie-Leek

I have trouble to keep up with all the info and how to use it in the best way. Luckily my team members are the best and help me through the questions I have. I had a struggle to get last week and this week deployed. But got some awesome help from Ida, a big shout out to you <3!

If I had more time I would read up more and practice on backend in generall and how to connect it to the frontend.

2021-05-27 21:59 UTC, sandra-wallen approved these changes
Great job on this project! I'm sorry to hear you struggled with deployment, I did as well it can really be tricky sometimes 🙈, but happy to hear that you solved it 😀.

Your project ticks off all the blue requirements and your code is easy to read! See my comments for more specific thoughts. 

Maybe you could add more to your readme file, I know it can be a bit hard sometimes to come up with content for the readme, but think of what a viewer outside of Technigo would like to read about the project. Suggestions for the readme could be more of a description about the project, the purpose, the making of it, the end points etc. 😊

2021-05-27 21:59 UTC, sandra-wallen commented on server.js
> +})
Nice that you list the endpoints here! :D

2021-05-30 16:32 UTC, KarolCislowski requested changes
Your code is nice but:
-I really want to share smiles with others.- message field is not a good candidate for a unique property. 
-I want to see it in action so I need to have a link to the frontend 😸

2021-05-30 16:32 UTC, KarolCislowski commented on server.js
> +    unique: true,
why you set it as unique? Can't I share the same happiness with others? 😭

2021-05-30 16:32 UTC, KarolCislowski commented on server.js
> +    )
💯

2021-05-30 16:32 UTC, KarolCislowski commented on server.js
> +  }
Remember to always restrict access to all endpoints which can manipulate your data stored in your DB.

2021-05-30 16:32 UTC, KarolCislowski commented on server.js
> +    }
🧹

2021-06-12 12:57 UTC, KarolCislowski requested changes
I still need to get the Netlify link to test your app, and I still think that making the message the unique field is not a great idea.

2021-06-12 13:09 UTC, Yennie-Leek commented
Forgot to and the link.
It’s in the readme  now and I have also removed the ”unique” requirement in message.

Yennie


On 12 Jun 2021, at 14:57, Karol Cislowski ***@***.******@***.***>> wrote:



@KarolCislowski requested changes on this pull request.

I still need to get the Netlify link to test your app, and I still think that making the message the unique field is not a great idea.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTechnigo%2Fproject-happy-thoughts-api%2Fpull%2F153%23pullrequestreview-682323791&data=04%7C01%7C%7Ccaa48d99449e4d7e805608d92da19e48%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637590994429815794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vmq1pP%2FzxcOXXcXgIhxbz%2F678bG2ch1ML345uR5rkTk%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASDKI7OWQRXPLB5EWZOPQI3TSNKTBANCNFSM45JJPACQ&data=04%7C01%7C%7Ccaa48d99449e4d7e805608d92da19e48%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637590994429815794%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bRk4lHqxjpDBBjyLb79l%2FA%2FcSJH2SuUbJb5gJMI9Vfc%3D&reserved=0>.

2021-06-19 13:02 UTC, KarolCislowski approved these changes
Great APP

2022-04-21 14:28 UTC, closed without merging