Happy Thoughts API, Hannah Jesinkey
Technigo/project-happy-thoughts-api pull request #156
Opened 2021-05-21 18:49 UTC by jesinkey

Deployed app: https://happy-thoughts-hannahj.herokuapp.com/

2021-05-28 20:22 UTC, jessika-hage approved these changes
I don't have anything to comment on other than that the code looks very nice and it is easy to read and understand! Great job! :D

2021-05-30 16:50 UTC, KarolCislowski requested changes
Your code looks nice but you need to provide a link to the frontend connected to this API for testing 😸

2021-05-30 16:50 UTC, KarolCislowski commented on README.md
some documentation on how to use your API would be nice 🤓

2021-05-30 16:50 UTC, KarolCislowski commented on server.js
> +    maxlength: 140,
Nicely configured field 👍🏻

2021-05-30 16:50 UTC, KarolCislowski commented on server.js
> +    .exec();
💯

2021-05-30 16:50 UTC, KarolCislowski commented on server.js
> +      }
💯

2021-05-30 16:50 UTC, KarolCislowski commented on server.js
> +});
remember to restrict endpoints that can manipulate with data stored in your DB 🤓

2021-05-30 17:05 UTC, jesinkey commented
Sorry! Here is the frontend link: https://happy-thoughts-hj.netlify.app/

2021-06-12 15:46 UTC, KarolCislowski approved these changes
Great App

2022-04-21 14:28 UTC, closed without merging