Happy Thoughts API by Irina Jekabsone
Technigo/project-happy-thoughts-api pull request #164
Opened 2021-05-22 17:19 UTC by Irina-web-dev

https://app-happy-thoughts.herokuapp.com/

2021-05-26 20:23 UTC, MarySparrow approved these changes
Always a pleasure reviewing your code, I have tested all your endpoints and error messages in Postman and it works like clockwork . Marvellous job Irina 🤩 I really cannot find anything to comment except it is all very nice done. 🌟🌟

2021-05-26 20:23 UTC, MarySparrow commented on server.js
> +
Great with an overview for all endpoints here 👍 👍

2021-05-26 20:23 UTC, MarySparrow commented on server.js
> +    res.json(newThought)
Great that you know both ways of writing this! Short and nice 🔥

2021-05-26 20:23 UTC, MarySparrow commented on server.js
>  })
Here is a console log that we can remove ✏️

2021-05-30 17:53 UTC, KarolCislowski requested changes
Your code looks great but you need to provide a link to the frontend connected to this API 😸

2021-05-30 17:53 UTC, KarolCislowski commented on README.md
> +This endpoint doesn't require a JSON body. Given a valid thought id in the URL, the API finds that thought, and update its hearts property to add one heart. If the id is invalid, an error message wil
Nice documentation 👍🏻

2021-05-30 17:53 UTC, KarolCislowski commented on server.js
> +    unique: true,
The message is not a good field to make it unique. if 3 recruiters come and send "testing" 2 of them will think it is not working 😭

2021-05-30 17:53 UTC, KarolCislowski commented on server.js
> +    maxlength: [140, 'Your thought is too long']
🥇

2021-05-30 17:53 UTC, KarolCislowski commented on server.js
> +      .limit(per_page)//.skip(20).limit(20) if you want to show another 20
👍🏻

2021-05-30 17:53 UTC, KarolCislowski commented on server.js
> +})
Remember to restrict access to this endpoint because not all users should have access to this functionality 🤓

2021-05-30 17:53 UTC, KarolCislowski commented on server.js
> +        new: true
💯

2021-05-30 17:53 UTC, KarolCislowski approved these changes
My bad! It is in the ReadMe 😺

2022-04-21 14:28 UTC, closed without merging