project-happy-thoughts-api - Felicia Liabäck Löwstett
Technigo/project-happy-thoughts-api pull request #167
Opened 2021-05-23 09:57 UTC by liaback-lowstett

2021-05-30 18:22 UTC, KarolCislowski requested changes
The code looks great but you need to provide a link to the frontend connected to it.

2021-05-30 18:22 UTC, KarolCislowski commented on server.js
> +    maxlength: [140, "The messages needs to be less than 140 characters."],
Nicely configured field 👍🏻

2021-05-30 18:22 UTC, KarolCislowski commented on server.js
> +  const allThoughts = await Thought.find().sort( { createdAt: -1 } ).limit(20)
👍🏻

2021-05-30 18:22 UTC, KarolCislowski commented on server.js
> +    const updatedThought = await Thought.findOneAndUpdate({ _id: id }, { $inc: { hearts: 1 }}, { new: true });
💯

2021-05-30 18:22 UTC, KarolCislowski commented on server.js
> +// });
Remember to restrict access to these endpoints because not all users should have access to these functionalities 🤓

2021-06-17 05:53 UTC, liaback-lowstett commented
Add netlify link

2021-06-19 13:00 UTC, KarolCislowski approved these changes
Great APP 🥇

2022-04-21 14:28 UTC, closed without merging