Technigo Boot Camp week 19: Happy Thoughts API - Ida Sylvén
Technigo/project-happy-thoughts-api pull request #169
Opened 2021-05-23 12:51 UTC by idasylven

Link to deployed app: https://is-happy-thoughts.herokuapp.com/

My reflections on how this week's project turned out: I thought this was a fun assignment, specially since it was relating to the previous Happy Thoughts project. It was nice to feel a bit more comfortable with the syntax in general and with the process of deploying the API and the database itself.  

Things I'd like to have clarified or explained in more detail: Nothing in particular at this current stage.

2021-05-26 16:34 UTC, TobiasHagberg approved these changes
A nice project which meets all the requirements for the week. It's especially fun to read about the added motivation of being a full stack developer. Well done 👏😊🎉

2021-05-26 16:34 UTC, TobiasHagberg commented on server.js
> +import listEndpoints from 'express-list-endpoints'
Always a nice touch for simple documentation 📑

2021-05-26 16:34 UTC, TobiasHagberg commented on server.js
>  app.use(cors())
Quick reminder from this weeks labs. The use of cors without specifying exceptions is what enables access from all domains.

2021-05-26 16:34 UTC, TobiasHagberg commented on server.js
> +    maxlenght: [140, "Sorry, you message is unfortunately exceeding the limit of 140 characters"]
Like the extra effort put into these explanations

2021-05-26 16:34 UTC, TobiasHagberg commented on .env
> +RESET_DB = true
You have forgot to list your .env to the gitnore file and are therefore sharing sensitive data with the world 🌎😬

2021-05-30 18:28 UTC, KarolCislowski requested changes
The code looks great but you need to provide a link to the frontend connected to it 😸

2021-05-30 18:28 UTC, KarolCislowski commented on server.js
> +    maxlenght: [140, "Sorry, you message is unfortunately exceeding the limit of 140 characters"]
Nicely configured field 👍🏻

2021-05-30 18:28 UTC, KarolCislowski commented on server.js
> +    const allThoughts = await Thought.find().sort({ createdAt: -1 }).limit(20)
👍🏻

2021-05-30 18:28 UTC, KarolCislowski commented on server.js
> +    const updatedThought = await Thought.findOneAndUpdate(thoughtId, { $inc: { hearts: 1 } }, { new: true })
💯

2021-05-30 18:28 UTC, KarolCislowski commented on server.js
> +// })
Remember to restrict access to these endpoints because not all users should have access to these functionalities 🤓

2021-05-31 20:10 UTC, idasylven commented
Thank you for your comments! 💫  I didn't take connecting them as a necessity at the point of submission, as it wasn't listed among the general or blue level requirements. But I did indeed have future plans to do so - and now I have! Please find updated README and Pull Request with the link of the connected frontend project 🔄  👍🏻  😊

2021-06-12 13:00 UTC, KarolCislowski approved these changes
Great APP

2022-04-21 14:28 UTC, closed without merging