Project-happy-thoughts-api- Marielle Ohlsson
Technigo/project-happy-thoughts-api pull request #174
Opened 2021-05-23 14:53 UTC by Marielle8

I aimed for the blue requirments int this project.

Link to deployed frontend on netlify: https://happy-thoughts8.netlify.app/

Link to deployed backend on heroku: https://marielles-happy-thoughts-api.herokuapp.com/thoughts

2021-05-27 07:52 UTC, johlofg requested changes
Overall a good project with clean code and good comments. Everything look alright and it seems that the error handeling is working too. But I cant get the application to work?

2021-05-27 07:52 UTC, johlofg commented on server.js
>  })
Good comment and nice with _ instead of req.

2021-05-31 04:32 UTC, KarolCislowski requested changes
Your code looks good, but your deployed server returns a 503 error
![image](https://user-images.githubusercontent.com/50926159/120139952-d3c68980-c1d9-11eb-8911-278dbe8335e1.png)
Check if you have correctly configured connection with mongo atlas

2021-05-31 04:32 UTC, KarolCislowski commented on server.js
> +    maxlenght: 140
Nicely configured field 👍🏻

2021-05-31 04:32 UTC, KarolCislowski commented on server.js
> +    const updatedThought = await Thought.findOneAndUpdate({ _id: thoughtId }, { $inc: { hearts: 1 } }, { new: true })
💯

2021-05-31 04:32 UTC, KarolCislowski commented on server.js
> +  const thoughts = await Thought.find().sort({ createdAt: 'desc' }).limit(20).exec()
👍🏻

2021-05-31 06:46 UTC, johlofg approved these changes
Snyggt!

2021-06-19 13:04 UTC, KarolCislowski approved these changes
Great app 🥇

2022-04-21 14:28 UTC, closed without merging