Happy-thoughts-api-Ekaterina
Technigo/project-happy-thoughts-api pull request #176
Opened 2021-05-23 16:23 UTC by klimenko3007

2021-05-24 16:21 UTC, rubmaigut approved these changes
Good code, clear, and easy to read. !

2021-05-24 16:21 UTC, rubmaigut commented on server.js
> +      message: "Cursing words are not allowed"
Nice validator "Only positive thoughts"

2021-05-24 16:21 UTC, rubmaigut commented on server.js
> +    res.status(400).json(error)
Ohh good way to make pagination, you inspire me !!

2021-05-24 16:26 UTC, rubmaigut approved these changes
Good code, clear, and easy to read. !

2021-05-24 16:27 UTC, rubmaigut commented
Good work!

2021-05-30 19:46 UTC, KarolCislowski requested changes
Your code looks great but you need to provide a link to the frontend connected to this API.

2021-05-30 19:46 UTC, KarolCislowski commented on server.js
> +      message: "Cursing words are not allowed"
Nicely configured field 🤓

2021-05-30 19:46 UTC, KarolCislowski commented on server.js
> +        $limit: +perPage || 20
awesome 😻

2021-05-30 19:46 UTC, KarolCislowski commented on server.js
> +    const thoughtUpdate = await Thought.findByIdAndUpdate(id, { $inc: { hearts: 1 } }, { new: true })
💯

2021-06-12 13:08 UTC, KarolCislowski approved these changes
Great APP!

2022-04-21 14:28 UTC, closed without merging