Project Happy Thought API week 19
Technigo/project-happy-thoughts-api pull request #178
Opened 2021-05-23 17:40 UTC by FD000

2021-05-26 21:34 UTC, Martno96 requested changes
The API works well for the most part! :D I have left some comments on security (hence the requested changes) and some food for thought regarding user experience, but the functionality is all there otherwise. Just remember to also update your frontend to seal the deal ^^ keep up the good work!

2021-05-26 21:34 UTC, Martno96 commented on server.js
> +    unique: true,
With messages needing to be unique, two user wouldn't be able to send messages worded the same way!

2021-05-26 21:34 UTC, Martno96 commented on server.js
> +    res.status(400).json({ message: 'Invalid request', error })
Good that you are returning descriptive error codes :D

2021-05-26 21:34 UTC, Martno96 commented on server.js
> +      res.status(400).json({ error: 'Duplicated value', field: error.keyValue })
Good that you send a more descriptive error message than the standard code 400 :)

2021-05-30 19:57 UTC, KarolCislowski requested changes
Your code looks great but you need to provide a link to the frontend connected to it 🤓

2021-05-30 19:57 UTC, KarolCislowski commented on server.js
> +    unique: true,
The message is not a good field to make it unique. if 3 recruiters come and send "testing" 2 of them will think it is not working 😭

2021-05-30 19:57 UTC, KarolCislowski commented on server.js
> +  const allThoughts = await Thought.find().sort({ createdAt: 1 }).limit(20)
👍🏻

2021-05-30 19:57 UTC, KarolCislowski commented on server.js
> +})
Remember to restrict access to these endpoints because not all users should have access to these functionalities 🤓

2021-05-30 19:57 UTC, KarolCislowski commented on server.js
> +      }
💯

2021-05-30 19:57 UTC, KarolCislowski commented on server.js
> +//mongodb+srv://myUser:myuserpassword@cluster0.prpaq.mongodb.net/happyThoughts?retryWrites=true&w=majority
And change your passwords 🙀

2021-06-08 06:24 UTC, KarolCislowski requested changes
You still need to connect it to the frontend and provide a Frontends link in the readme file :)

2021-06-19 11:10 UTC, KarolCislowski approved these changes
Nice app, but you need to change sorting to descending. Great Job 🥳

2021-06-19 11:10 UTC, KarolCislowski commented on server.js
> +  const allThoughts = await Thought.find().sort({ createdAt: 1 }).limit(20)
my bad createdAt should be `-1`

2022-04-21 14:28 UTC, closed without merging