project-happy-thoughts-api- Maidelin Rubio
Technigo/project-happy-thoughts-api pull request #189
Opened 2021-05-23 21:31 UTC by rubmaigut

For the happy Thoughts project I created the following features:

- User login: with options to create a new user (POS - https://happy-thoughts-api-mongodb.herokuapp.com/user/create) and validate existing users ( GET- https://happy-thoughts-api-mongodb.herokuapp.com/users/ ) 
- Get happy Thoughts to show the last 20 messages. (POS-https://happy-thoughts-api-mongodb.herokuapp.com/)
- Post new messages, it´s required username (POS- https://happy-thoughts-api-mongodb.herokuapp.com/thoughst)
- Post Like to a message. ( POS - https://happy-thoughts-api-mongodb.herokuapp.com/thoughts/id/like)

2021-05-26 20:43 UTC, tuttibalutti requested changes
Nice API, Maide🤩  👏  I like how you created the array to keep track of hashtags, supercool! I'm going to request changes just to clean up the code from console logs and some outcommented code. Well done!🥳

2021-05-26 20:43 UTC, tuttibalutti commented on server.js
> +  })
Cool🤓

2021-05-29 20:09 UTC, rubmaigut commented on server.js
> +const Thought = mongoose.model("Thoughts", {
Thank you, I will keep it in mind for future projects. I have changed it.

2021-05-29 20:12 UTC, rubmaigut commented on server.js
> +    maxLength:140
I didn't remember this, I put it on the camelCase because I read it in the documentation but I don't know if I should change it.

2021-05-29 20:16 UTC, rubmaigut commented on server.js
> +    console.log(newUser)
ready!

2021-05-29 20:16 UTC, rubmaigut commented on server.js
> +  console.log(pagination) */
ready!

2021-05-29 20:19 UTC, rubmaigut commented on server.js
> +  })
Thank you! :)

2021-05-31 03:33 UTC, KarolCislowski approved these changes
Great API 🥇

2021-05-31 03:33 UTC, KarolCislowski commented on README.md
> +- Post Like to a message. ( POS - https://happy-thoughts-api-mongodb.herokuapp.com/thoughts/id/like)
Nice documentation 👍🏻

2021-05-31 03:33 UTC, KarolCislowski commented on server.js
> +    const allThoughts = await Thought.find().limit(req.query.limit).sort({createDate: -1})
👍🏻

2021-05-31 03:33 UTC, KarolCislowski commented on server.js
> +    maxLength:140
It works nicely 🥳 Maybe it was something in older versions... I checked documentation and camelCase there is... 🤓

2021-05-31 03:33 UTC, KarolCislowski commented on server.js
> +  })
impressive logic, but isn't it a good idea to do it on the client's side?  String operations are pretty resource-heavy. The user needs to perform it only for 1 small message at a time and the server needs to cover it for all incoming messages. When your app becomes a hit this one extra operation can heavily slow down your server.

2021-05-31 03:33 UTC, KarolCislowski commented on server.js
> +    await Thought.findByIdAndUpdate(id,{hearts:thoughtsId.hearts+1})
💯

2021-05-31 03:33 UTC, KarolCislowski commented on server.js
> +})
Nice that you provided a simple user system, now after auth project you can secure them 🤓

2022-04-21 14:28 UTC, closed without merging