Happy thoughts API - Estefanía
Technigo/project-happy-thoughts-api pull request #192
Opened 2021-05-24 19:59 UTC by esteficodes

2021-05-28 19:05 UTC, dannuzak reviewed
Hi Estefania!
Good job with this project! I also learned how to limit the amount of thoughts display while doing your code review. I am aware you will keep working a bit more on this project but so far looks great! 🌻

2021-05-28 19:05 UTC, dannuzak commented on README.md
> +https://happy-thoughts-api-estefania.herokuapp.com/
The endpoints worked fine for me! Looking forward to seeing your API implemented in your frontend project! 🦄

2021-05-31 03:48 UTC, KarolCislowski requested changes
Your code looks great but you need to provide a link to the frontend connected to it 😸

2021-05-31 03:48 UTC, KarolCislowski commented on server.js
> +        return /^[^0-9]+$/.test(value);
ok... but why? Karol loves numbers 😭

2021-05-31 03:48 UTC, KarolCislowski commented on server.js
> +    unique: true,
The message is not a good field to make it unique. if 3 recruiters come and send "testing" 2 of them will think it is not working 😭

2021-05-31 03:48 UTC, KarolCislowski commented on server.js
> +  res.json(allThoughts);
👍🏻

2021-05-31 03:48 UTC, KarolCislowski commented on server.js
> +})
Remember to restrict access to this endpoint because not all users should have access to this functionality 🤓

2021-05-31 03:48 UTC, KarolCislowski commented on server.js
> +      }
💯

2021-06-12 13:01 UTC, KarolCislowski approved these changes
Great APP!

2022-04-21 14:28 UTC, closed without merging