Week 19 Happy Thoughts Api - Malin Göthe
Technigo/project-happy-thoughts-api pull request #194
Opened 2021-05-26 19:06 UTC by M4L5

Live project: https://goethe-happy-thoughts.herokuapp.com/
Will add readme and clean up after peer review :)

2021-05-26 19:46 UTC, Sofarz requested changes
Malin! 🌷 
Great work on this weeks project! However there are some things you need to fix to make it possible to add likes. Look at my comment regarding line 73 :).
A tip for the future would be to add more comments, to make it easier for yourself to follow if you go back to the code, as well as for others 😃 .

2021-05-26 19:46 UTC, Sofarz commented on server.js
> +mongoose.connect(mongoUrl, { useNewUrlParser: true, useUnifiedTopology: true, useCreateIndexes: true })
If I'm not mistaking it should be useCreateIndex and not indexes here.

2021-05-26 19:46 UTC, Sofarz commented on server.js
> +})
Nice! 💯

2021-05-26 19:46 UTC, Sofarz commented on server.js
> +    const newLike = await Thought.findByIdAndUpdate({ id }, {$inc: {hearts: 1} })
It is not possible to add likes right now, I checked it in Postman and it does not work there, so there is something wrong in the backend. I believe that you only need to write id on line 73 and not { id } :)

2021-05-26 19:46 UTC, Sofarz commented on server.js
> +app.get('/thoughts', async (_, res) => {
Nice feature with the _ instead of req when it isn't used, but not know about that 👍

2021-05-31 03:54 UTC, KarolCislowski approved these changes
Great API but you need to work on your frontend 👨🏻‍🎨 🎨

2021-05-31 03:54 UTC, KarolCislowski commented on server.js
> +    maxlength: 140
Nicely configured field 👍🏻

2021-05-31 03:54 UTC, KarolCislowski commented on server.js
> +    const everyThought = await Thought.find().sort({ createdAt: -1 }).limit(20)
👍🏻

2021-05-31 03:54 UTC, KarolCislowski commented on server.js
> +    const newLike = await Thought.findByIdAndUpdate(id, {$inc: {hearts: 1} })
👍🏻

2022-04-21 14:28 UTC, closed without merging