Happy thoughts
Technigo/project-happy-thoughts-api pull request #366
Opened 2023-05-17 10:14 UTC by IrupePozoGraviz

API
https://irupe-happy-thoughts-api-kobjwpkrba-lz.a.run.app

happy thoughts frontend
https://joyful-nougat-d637a7.netlify.app/

2023-05-23 12:06 UTC, JohLeo approved these changes
Well structured code and easy to follow and read!  Such a great job! Nicely done!

2023-05-23 12:06 UTC, JohLeo commented on server.js
> +      message: "did not successfully"
You could maybe clearify this message a bit more! ;)

2023-05-23 12:06 UTC, JohLeo commented on server.js
> +    default: new Date()
Did you get this code to work? Impressed, I had to change it for it to log the time accordingly. Interesting!

2023-05-24 13:44 UTC, Nahnahke requested changes
Would like to start out by saying this is a job well done! Your code is short and concise and very easy to follow.

I added some small suggestions, like erasing the commented out code and another suggestion might be to add more description in your code about what all the different functions do.

Great going Irro, you did a truly great job with this!

2023-05-24 13:44 UTC, Nahnahke commented on README.md
> +happy thoughts frontend https://joyful-nougat-d637a7.netlify.app/
Excellent read me.

2023-05-24 13:44 UTC, Nahnahke commented on server.js
>  import mongoose from "mongoose";
Suggest you add Schema here in order to use const Schema on line 26.

2023-05-24 13:44 UTC, Nahnahke commented on server.js
> +const { Schema } = mongoose;
Add Schema in the imports in order to use const { Schema } here.

2023-05-24 13:44 UTC, Nahnahke commented on server.js
> +      message: "did not successfully"
Agree with Johanna on this one. A suggestion might be something like:

"Failed to retrieve thoughts"

2023-05-24 13:44 UTC, Nahnahke commented on server.js
> +   });*/
I suggets you remove the commented out part of the code :)

2023-05-24 13:44 UTC, Nahnahke commented on server.js
> + // POST thoughts/:thoughtId/like
Some real nice work below!

2023-05-24 13:44 UTC, Nahnahke commented on server.js
> +    res.status(400).json({ message: "Could not save your like", error: err.errors });
What does the "error: err.errors" do? Have not used the same approach, would be interesting to know!

2023-10-26 15:12 UTC, closed without merging