Happy Thoughts API Sofie
Technigo/project-happy-thoughts-api pull request #484
Opened 2024-05-18 12:54 UTC by SofieFerrari

## Netlify link
Backend: https://sofies-happy-thoughts-api.onrender.com/
Frontend: https://bucolic-beignet-3163b4.netlify.app/

2024-05-22 14:37 UTC, HIPPIEKICK requested changes
Looks good! Just have a look at the like function and let me know when I can check again 🌻

2024-05-22 14:37 UTC, HIPPIEKICK commented on server.js
> +	if (thoughts.length === 20 || thoughts.length < 20) {
This could be written as 
`if (thoughts.length <= 20)`

2024-05-22 14:37 UTC, HIPPIEKICK commented on server.js
> +	console.log({ id })
Remove console.logs in production

2024-05-22 14:37 UTC, HIPPIEKICK commented on server.js
> +app.get('/thoughts/:id', async (req, res) => {
Nice with an extra endpoint 👍

2024-05-22 14:37 UTC, HIPPIEKICK commented on server.js
> +	const { message, createdAt } = req.body
Should createdAt really come from the body?

2024-05-22 14:37 UTC, HIPPIEKICK commented on server.js
> +app.post('/thoughts/:id/like', async (req, res) => {
I can't see anything wrong here, but your like function isn't working in the frontend 👀 Could you please have a look and reach out on SO if you need 😇

2024-06-24 11:13 UTC, SofieFerrari commented
Hej Matilda, jag hade missat detta! Men jag har löst det nu, jag hade råkat (lol) sätta mina hearts som immutable i min Thoughts model... dumt! Men fixat nu och nu funkar det!

2024-06-24 13:23 UTC, AntonellaMorittu approved these changes

2025-01-08 21:58 UTC, closed without merging