Pull request for happy thoughts api
Technigo/project-happy-thoughts-api pull request #91
Opened 2021-01-07 22:37 UTC by Katsiez

2021-01-10 14:14 UTC, liza-minican reviewed
Hey Kat,

I always admire your desire to learn more and that you are never scared of implementing new things!!!! I've got inspired by you many times!! Keep up your curiosity and good work!!! You did a great job with the project. 
https://happy-thoughts-kat.netlify.app/ this page doesn't show your form. I checked your code in the happy thoughts project and it looks like you connected the links correctly. Not sure why it is happening, maybe there is an issue with connection to atlas. Hopefully our code coaches can help you fix that. 
Good luck with everything!! Be proud!

2021-01-10 14:14 UTC, liza-minican commented on server.js
> +    .exec();
Not sure what this code does as I don´t see you using this const later on in the code.

2021-01-19 09:56 UTC, KarolCislowski requested changes
Great work with the API, but your frontend do not show anything. I looked inside and I have some idea how to fix it:
in app.js in line 45:
  `{thoughts.map(thought => (` 
change to:
 ` {thoughts?.map(thought => (`
 
this `?` makes map start only if your array is not empty, so it will not crash before `useEffect()` will start.

2021-01-19 11:12 UTC, Katsiez commented
Thanks for your comment, Karol! I knew the frontend wasn't connecting for some odd reason, made the change you suggested and I am still experiencing the same issue, sadly.

2021-01-19 11:29 UTC, KarolCislowski commented
Your api is returning 
```
{
  "pages": 1,
  "thoughts": [...]
 }
  ```
  So you need to access `thoughts` inside your `json` in `useEffect`:
  `.then(json => setThoughts(json.**thoughts**))`

2021-03-11 09:43 UTC, closed without merging